README: describe architectures support for Salt deps on Linux distros
saltstack/salt-bootstrap pull request #1029
Opened 2017-02-13 09:37 UTC by vutny

### What does this PR do?
It recommends to use `git` bootstrap mode with some options to get Salt running on "foreign" CPU architectures besides `x86_64`. This is proven to work on Debian and Ubuntu, but also may be applicable for other Linux distros, for which Salt does not build packages at all.

### What issues does this PR fix or reference?
This should resolve issue #1004

2017-02-13 17:14 UTC, rallytime requested changes
Thanks @vutny - Just one small comment and then I can get this in.

2017-02-13 17:14 UTC, rallytime commented on README.rst
> +Since Salt has written in Python, the packages available from `SaltStack's corporate repository`_
`has written` should be `is written` here.

2017-02-14 09:28 UTC, vutny commented on README.rst
> +Since Salt has written in Python, the packages available from `SaltStack's corporate repository`_
Oh sure, thanks. Need to improve my grammar :)

2017-02-14 09:32 UTC, vutny commented
@rallytime , corrected.

2017-02-14 15:41 UTC, rallytime approved these changes

2017-02-14 15:41 UTC, rallytime commented
Thanks!

2017-02-14 15:41 UTC, merged

2018-05-07 19:49 UTC, alexandruavadanii commented on README.rst
> +``AArch32`` (``armhf``), which is limited for Debian/Raspbian 8 platforms.
I think this might be misleading. armhf is ARMv7 (see [1]), while AArch32 is the 32-bit mode of operation / instruction set for ARMv8.
So both `AArch64` and `AArch32` are actually ARMv8.
[1] https://en.wikipedia.org/wiki/ARM_architecture

2018-05-08 13:07 UTC, vutny commented on README.rst
> +``AArch32`` (``armhf``), which is limited for Debian/Raspbian 8 platforms.
Hi @alexandruavadanii 
In Debian ports, the `armhf` (which is [ARM hard-float](https://wiki.debian.org/ArmHardFloatPort)) only supports 32-bit Armv7 CPU with at least Thumb-2 and VFP3D16, which is ARMv7-A therein referred to as "AArch32".
I'm not an ARM architecture expert, but that seems correct to me.

More info here: https://www.debian.org/ports/arm/