Allow -R option to work for Debian/Ubuntu
saltstack/salt-bootstrap pull request #1045
Opened 2017-04-13 20:25 UTC by rallytime

### What does this PR do?
Allows the `-R` option to work with Debian-based distributions.

I put together the initial commits for this a while ago, but never finished up and tested the change. After a quick test and a small change, this is ready to go.

### What issues does this PR fix or reference?
Fixes #968

### Previous Behavior
The `-R` option was restricted to only working on RHEL-based distributions.

### New Behavior
The `-R` option has been expanded to also work with Debian/Ubuntu.

2017-04-14 08:39 UTC, vutny requested changes
@rallytime This is cool!

I just have couple of minor suggestions here...

2017-04-14 08:39 UTC, vutny commented on bootstrap-salt.sh
> +    _REPO_URL="repo.saltstack.com"
I think, maybe it's better to put the default `_REPO_URL` value even earlier, where all default settings already defined?
And then just override it here. Just to keep all similar things in one place.

See line 194: https://github.com/saltstack/salt-bootstrap/pull/1045/files#diff-a8778033f6225c137abf05cf8d0bb113L194

2017-04-14 08:39 UTC, vutny commented on bootstrap-salt.sh
> +        # Versions starting with 2015.5.6, 2015.8.1 and 2016.3.0 are hosted at $_REPO_URL
Do we really need to put the variable in the comment here? ;-)

2017-04-14 10:13 UTC, s0undt3ch approved these changes
@vutny's suggestions are great.

2017-04-14 15:50 UTC, rallytime commented on bootstrap-salt.sh
> +    _REPO_URL="repo.saltstack.com"
Ah, yes, good idea.

2017-04-14 15:50 UTC, rallytime commented on bootstrap-salt.sh
> +        # Versions starting with 2015.5.6, 2015.8.1 and 2016.3.0 are hosted at $_REPO_URL
Heh, nope. I'll fix that.

2017-04-14 15:56 UTC, rallytime commented
Thanks for the suggestions @vutny! I have updated this PR with your suggestions.

2017-04-18 14:18 UTC, vutny approved these changes

2017-04-18 14:18 UTC, vutny commented on bootstrap-salt.sh
> +_REPO_URL="repo.saltstack.com"
:+1:

2017-04-18 14:52 UTC, merged