Add KDE neon...
saltstack/salt-bootstrap pull request #1058
Opened 2017-04-26 08:03 UTC by EHJ-52n

### What does this PR do?
Add support for KDE neon to `__ubuntu_derivatives_translation()`

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-bootstrap/issues/1050 Cannot install standalone minion on kde neon

### Previous Behavior
Salt could *not* be installed on kde neon.

### New Behavior
Salt can be installed on kde neon.

2017-04-26 08:08 UTC, vutny requested changes
@EHJ-52n Awesome, thank you!

But could you please update the README section as well?
https://github.com/saltstack/salt-bootstrap/blob/develop/README.rst#ubuntu-and-derivatives

2017-04-27 08:50 UTC, EHJ-52n commented
@vutny Added a line as requested about kde neon to `README.rst`.

2017-04-27 08:54 UTC, vutny approved these changes
:+1:

2017-04-27 15:26 UTC, rallytime approved these changes

2017-04-27 15:26 UTC, merged