Declare End-Of-Life for Ubuntu 12.04 LTS
saltstack/salt-bootstrap pull request #1080
Opened 2017-05-25 08:00 UTC by vutny

### What does this PR do?
It drops support for Ubuntu LTS 12.04 which reached EOL at April 28, 2017.
Also, installation on derivatives forked from 12.04 release is no longer possible.
The README has been updated accordingly.

### Previous Behavior
Salt installation on Ubuntu 12.04 was possible.

### New Behavior
The script notifies a user that Ubuntu 12.04 reached EOL and no longer supported.

2017-05-25 16:05 UTC, rallytime requested changes
Very nice! Thanks for cleaning this up. I like moving the EOL checks up further in the script. I had some small comments on that function. I know that was largely copy/pasted from below, but we might as well fix it now. :)

2017-05-25 16:05 UTC, rallytime commented on bootstrap-salt.sh
> +            if [ "$DISTRO_MAJOR_VERSION" -lt 23 ]; then
I think 23 is EOL too, so let's make that 24 instead.

Also, can you make the comment line above match? (18 should be 24)

2017-05-25 16:05 UTC, rallytime commented on bootstrap-salt.sh
> +            # CentOS versions lower than 5 are no longer supported
Comment should be `lower than 6` for clarity.

2017-05-25 16:05 UTC, rallytime commented on bootstrap-salt.sh
> +            # Red Hat (Enterprise) Linux versions lower than 5 are no longer supported
Same thing here, this should read `lower than 6`.

2017-05-25 16:05 UTC, rallytime commented on bootstrap-salt.sh
> +            # Oracle Linux versions lower than 5 are no longer supported
Same thing here. There are a couple more below this comment that should be updated as well, but I won't add a comment for each one.

2017-05-25 16:07 UTC, rallytime commented on bootstrap-salt.sh
> +            if [ "$DISTRO_MAJOR_VERSION" -lt 23 ]; then
This change would need an update to the README here as well.

2017-05-26 07:13 UTC, vutny commented on bootstrap-salt.sh
> +            if [ "$DISTRO_MAJOR_VERSION" -lt 23 ]; then
@rallytime I think it would be better if I make a change for Fedora in separate PR just to make things clear and separate concerns.

2017-05-26 07:15 UTC, vutny commented on bootstrap-salt.sh
> +            # CentOS versions lower than 5 are no longer supported
Yeah, I'll fix this and later comments to match real comparisons. Thanks for spotting that!

2017-05-26 07:23 UTC, vutny commented
@rallytime I've fixed the comments in `__check_end_of_life_versions()` function. I will drop Fedora 23 support with another PR later. Thanks for review.

2017-05-26 15:21 UTC, rallytime approved these changes

2017-05-26 15:21 UTC, rallytime commented
@vutny sounds good. thanks!

2017-05-26 15:21 UTC, merged