FEAT: add support for OS X in bootstrap script.
saltstack/salt-bootstrap pull request #1104
Opened 2017-06-19 19:46 UTC by cournape

### What does this PR do?

Add support for bootstrapping salt minions on OS X

While the PR adds support for 10.9 upward, since the latest installer only supports 10.11 upward, this effectively supports 10.11 and above only. If the salt minion package is built with https://github.com/saltstack/salt/pull/37858, then the bootstrap script will effectively support 10.9 and above.

2017-06-20 08:17 UTC, vutny requested changes
@cournape Finally! Good work.
There are several lint check violations, however they are trivial to fix. Please take a look at my comments below.

Also, would you mind to update the README file about OS X support as well?

2017-06-20 08:17 UTC, vutny commented on bootstrap-salt.sh
> +    DISTRO_MINOR_VERSION=$(echo ${DISTRO_VERSION} | cut -d. -f 2)
Lint checker fails on the two lines above: remember to quote variable and command substitutions.

2017-06-20 08:17 UTC, vutny commented on bootstrap-salt.sh
> +        installer -pkg ${target} -target / || return 1
Same here, `${target}` should be surrounded with double quotes.

2017-06-20 09:08 UTC, cournape commented
@vutny how does that look now ?

2017-06-20 09:16 UTC, vutny approved these changes
This is perfect. Thank you.

@rallytime, I think we are good to go.

2017-06-30 17:15 UTC, rallytime commented
Thank you for getting this support started @cournape! My main concern with this PR as it stands right now is that there are references to exact installer versions in the `install_darwin_stable` function. We should be able to install any version of salt, and not be pinned to a single version. 

Can you refactor that function to work for multiple versions of salt?

2017-07-21 19:12 UTC, rallytime commented
Bump @cournape - did you see my comment above?

2017-08-15 15:25 UTC, rallytime commented
@cournape bump

2017-09-07 14:59 UTC, rallytime commented
Closing due to no response.

We can certainly open this again when the concerns above are addressed.

2017-09-07 14:59 UTC, closed without merging

2019-05-24 16:15 UTC, tiyab commented
Hi, sorry for digging out this topic.
As I was looking a way to automate dotfiles installation on MacOS + Linux via SaltStack, I stumble upon this.
@rallytime The issue is, it will be difficult to not hardcode the MacOS version in the script as there is no `latest` directory for OSX.
If you look how the release are done for Debian or RHEL, you will found a `latest` directory to which the script is referring to.
Until this is change I don't see a viable way to change the PR.