Only install Python version if "-y" is defined
saltstack/salt-bootstrap pull request #1124
Opened 2017-08-08 17:05 UTC by rallytime

### What does this PR do?
Allows the `-x` option to be used _without_ the `-y` option. This is useful in situations where the ius-community repo and related Python version is already installed, but the pip packages still need to be installed.

Previously, both the `-x` and `-y` options were both required to run the Python installation and the pip dependency installation. This PR splits out the `-y` option requirement when `-x` is passed. That way, the `-y` option can be left off if the required python version and ius repo is already installed. Note that for the `-y` option being passed, `-x` is still required.

### What issues does this PR fix or reference?
Fixes #1121

### Previous Behavior
If the IUS repo was already installed (from a previous bootstrap run, or otherwise), the bootstrap script would error out on the next run:
```
INFO: Cloning Salt's git repository succeeded
INFO: Attempting to install a repo to help provide a separate python package
INFO: centos
INFO: Installing IUS repo
Loaded plugins: fastestmirror
Setting up Install Process
Examining /var/tmp/yum-root-WwmIVv/ius-release.rpm: ius-release-1.0-15.ius.centos6.noarch
/var/tmp/yum-root-WwmIVv/ius-release.rpm: does not update installed package.
Error: Nothing to do
ERROR: Failed to run install_centos_git_deps()!!!
DEBUG: Cleaning up the Salt Temporary Git Repository
DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
```

### New Behavior
The `-y` option is no longer required to trigger the pip installation using the python version defined with `-x`.

Example to install Python:
```
./bootstrap-salt.sh -y -x Python2.7 git v2017.7.0
```
Example to install pip dependencies where Python2.7 already exists on the VM:
```
./bootstrap-salt.sh -x Python2.7 git v2017.7.0
```

@Ch3LL Can you review this PR since this touches code that you added recently?

2017-08-15 15:18 UTC, vutny requested changes
👍 I like the idea of installing dependencies later in appropriate functions. But, I have spot some bug 😄

2017-08-15 15:18 UTC, vutny commented on bootstrap-salt.sh
> +        __yum_install_noinput "${__PACKAGES}" || return 1
This is not gonna work, because the package list would be passed as *single* argument.
That's why we have word splitting check bypassed here.

2017-08-15 15:20 UTC, rallytime commented on bootstrap-salt.sh
> +        __yum_install_noinput "${__PACKAGES}" || return 1
Oh, yes. Good catch.

2017-08-15 15:24 UTC, rallytime commented
@vutny Fixed.

2017-08-15 15:35 UTC, vutny approved these changes
LGTM

2017-08-16 13:43 UTC, Ch3LL approved these changes

2017-08-16 13:57 UTC, merged