Workaround gnupg2 not being proxy friendly, refs #1137
saltstack/salt-bootstrap pull request #1214
Opened 2018-04-04 18:12 UTC by EvaSDK

GnuPG2 does not support proxies using the CONNECT method which means only
transparent proxies are supported for encrypted traffic or one must degrade
security by disabling encryption during provisioning.

This commit switches back to curl piped to apt-key which is found on several software projects homepage, even salstack as a matter of fact: https://repo.saltstack.com/#debian, and works for all cases.

### What does this PR do?

Workaround GnuPG2 limitations when used behind proxies.

### What issues does this PR fix or reference?

Issue originally reported as #1137.

2018-04-05 13:02 UTC, vutny requested changes
Okay, `dirmngr` in Debian "jessie" is broken, that's why `apt-key adv` command fails silently.

But it seems that future versions of Debian and recent Ubuntus seems unaffected (I might be wrong, but assume GNU folks fix things, eventually). And of course it works if proxy is not the case.

So how about to add a fallback action piping downloaded key to `apt-key add` when `adv` command fails to connect?

I see no reason to completely sacrifice Dirmngr, because it serves it's security hardening purpose: checking for publicly revoked keys, when configured properly. So if SaltStack's signing key would be compromised (hope this never would happen!), the dirmngr will catch that.

I suggest to check the output of `apt-key adv` and then download the key only if `gpg` complains about "unable to fetch URI".

2018-04-05 13:02 UTC, vutny commented on bootstrap-salt.sh
> +    curl ${_CURL_ARGS} -f -s -S -L "$url" | apt-key add - ; return $?
You don't need to explicitly install and use `curl`, we have special wrapper function for downloading things: `__fetch_url` [here](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L755).

2018-04-05 13:42 UTC, rallytime commented
In addition to the comments above, this needs to be submitted against the `develop` branch and not `stable`. Stable only receives PRs when we merge `develop` into `stable` in preparation for a release.

2018-04-05 17:37 UTC, EvaSDK commented
Sorry, I worked against stable as this is what I needed for my production environment.

2018-04-05 17:44 UTC, EvaSDK commented
@vutny, not just Jessie, Stretch is affected as well. And I only provision LTS Ubuntu releases and Xenial ships with an older version of gnupg2 than Stretch. I'm ok with trying to use dirmngr if possible but my goal was to unbreak stable for me.

2018-04-08 17:35 UTC, vutny commented
@EvaSDK Indeed, I was wrong. A buggy version of `dirmngr` is present in `stretch`. `jessie` is not affected because there is older gnupg version used with `gnupg-curl` plugin, which apparently works with proxies.

You also could pre-accept download SaltStack key before running the bootstrap script to workaround the issue in current stable.

2018-04-09 16:35 UTC, rallytime commented
@EvaSDK Can you update your PR with the suggestion from @vutny to use the `__fetch_url` function and rebase this against the `stable` branch? That way we can get your fix in.

2018-04-24 14:44 UTC, rallytime commented
Since we haven't heard back here for a little while, I am going to close this as we do not merge changes in the `stable` branch directly.

If you want to rebase this change against the `develop` branch and incorporate the changes suggested above, we would certainly love to get this in.

We can of course continue the discussion here or on the new PR. Thanks all!

2018-04-24 14:44 UTC, closed without merging