Fix the variable ref from #803
saltstack/salt-bootstrap pull request #1229
Opened 2018-05-10 20:21 UTC by rallytime

The version of shellcheck that was previously running on bootstrap PRs was out of date and not catching the fact that the VIRTUAL_ENV variable didn't exist. That variable should be _VIRTUALENV_DIR instead.

Refs #803

2018-05-16 09:58 UTC, vutny requested changes

2018-05-16 09:58 UTC, vutny commented on bootstrap-salt.sh
> +        # shellcheck disable=34
I think this is rule [SC1090](https://github.com/koalaman/shellcheck/wiki/SC1090).
What is `34` by the way? I have tried that with ShellCheck 0.4.7 and it does not work.

2018-05-16 14:19 UTC, rallytime commented on bootstrap-salt.sh
> +        # shellcheck disable=34
You're right. I was using an old version of shellcheck.

2018-05-16 14:22 UTC, rallytime commented
@vutny Can you review one more time?

2018-05-17 06:23 UTC, vutny approved these changes
:+1:

2018-05-17 14:42 UTC, merged