[WIP] Remove support for Ubutu 17.10
saltstack/salt-bootstrap pull request #1260
Opened 2018-07-11 14:33 UTC by rallytime

Ubuntu 17.10 will be EOL any day now, as Ubuntu's release calendar says support will end in July 2018.

This commit removes support for the 17.10 (non-LTS) release. The README file was also updated to clarify when support for non-LTS releases will be removed from bootstrap.

**DO NOT MERGE UNTIL 17.10 IS OFFICIALLY EOL**

Release schedule: https://wiki.ubuntu.com/Releases

2018-07-12 01:25 UTC, KaiSforza approved these changes
:+1:

2018-07-13 12:22 UTC, vutny requested changes
This is great @rallytime .
I just have couple of minor things to suggest.

2018-07-13 12:22 UTC, vutny commented on bootstrap-salt.sh
> +    if [ "$DISTRO_MAJOR_VERSION" -gt 18 ]; then
Probably we would like the Bootstrap to be more future-proof and better detect some-day upcoming Ubuntu release 18.10. Something like this will be more robust:
```shell
    if [ "$DISTRO_MAJOR_VERSION" -gt 18 ] || [ "${DISTRO_VERSION}" = "18.10" ]; then
```

2018-07-13 12:22 UTC, vutny commented on README.rst
>  For example, when installing Salt on Ubuntu 17.10, the bootstrap script will setup the repository
While deprecating support for 17.10, maybe let's remove mentioning it and switch over number 18, what do you think?

2018-07-13 18:27 UTC, rallytime commented
@vutny Yes, good suggestions. I've incorporated them in the latest commit.

2018-07-20 16:59 UTC, merged