Update with 3006 stable installs
saltstack/salt-bootstrap pull request #1906
Opened 2023-03-29 21:58 UTC by garethgreenaway

### What does this PR do?
Adding support for installing 3006 via bootstrap.  Updating stable type to install onedir packages starting in 3006.

### What issues does this PR fix or reference?

2023-03-30 05:48 UTC, s0undt3ch approved these changes

2023-03-30 13:44 UTC, twangboy approved these changes

2023-04-14 16:23 UTC, s0undt3ch requested changes

2023-04-14 16:23 UTC, s0undt3ch commented on bootstrap-salt.sh
> +version = data['latest'][list(data['latest'].keys())[0]]['version']
```suggestion
version = data['latest'][list(data['latest'])[0]]['version']
```
No need to `.keys()`.

2023-04-14 16:23 UTC, s0undt3ch commented on bootstrap-salt.sh
> +      if [ "$(echo "$_ONEDIR_REV" | grep -E '(salt_rc)')" != "" ]; then
macOS RC's are also signed.

2023-04-14 16:23 UTC, s0undt3ch commented on bootstrap-salt.sh
> +      if [ "$(echo "$_ONEDIR_REV" | grep -E '(salt_rc)')" != "" ]; then
Basically, all, macOS packages are signed.

2023-04-14 16:23 UTC, s0undt3ch commented on bootstrap-salt.sh
> +      if [ "$(echo "$_ONEDIR_REV" | grep -E '(salt_rc)')" != "" ]; then
For >= 3006.0

2023-04-14 16:28 UTC, s0undt3ch approved these changes

2023-04-15 02:04 UTC, merged