cleanup old information in the README.rst file
saltstack/salt-bootstrap pull request #1955
Opened 2023-08-02 00:00 UTC by garethgreenaway

### What does this PR do?
cleanup old information in the README.rst file

2023-08-02 09:40 UTC, ITJamie commented
would it be worth having a substitution var in the rst file instead of declaring the explicit 3006.1 number over and over?

2023-08-02 12:39 UTC, s0undt3ch requested changes

2023-08-02 12:39 UTC, s0undt3ch commented on README.rst
> +the `SaltProject's corporate repository`_. See first example in the `Install using wget`_ section.
```suggestion
the `Salt Project's corporate repository`_. See first example in the `Install using wget`_ section.
```

2023-08-02 12:39 UTC, s0undt3ch commented on README.rst
> +If you want to install a package of a specific release version, from the SaltProject repo:
```suggestion
If you want to install a package of a specific release version, from the Salt Project repo:
```

2023-08-02 12:39 UTC, s0undt3ch commented on README.rst
> +If your host has Internet access only via HTTP proxy, from the SaltProject repo:
```suggestion
If your host has Internet access only via HTTP proxy, from the Salt Project repo:
```

2023-08-02 12:39 UTC, s0undt3ch commented on README.rst
> +Installing a specific version package from the SaltProject repo using ``wget``:
```suggestion
Installing a specific version package from the Salt Project repo using ``wget``:
```

2023-08-02 12:39 UTC, s0undt3ch commented on README.rst
> +Installing a target version package of Salt from the SaltProject repo:
```suggestion
Installing a target version package of Salt from the Salt Project repo:
```

2023-08-02 12:39 UTC, s0undt3ch commented on README.rst
> +Since Salt is written in Python, the packages available from the `SaltProject's corporate
```suggestion
Since Salt is written in Python, the packages available from the `Salt Project's corporate
```

2023-08-02 12:39 UTC, s0undt3ch commented on README.rst
> +repositories are not provided on the `SaltProject's Ubuntu repository`_ for the non-LTS release,
```suggestion
repositories are not provided on the `Salt Project's Ubuntu repository`_ for the non-LTS release,
```

2023-08-02 12:39 UTC, s0undt3ch commented on README.rst
> +for Ubuntu 20.04 from the `SaltProject's Ubuntu repository`_ and install the 20.04 packages.
```suggestion
for Ubuntu 20.04 from the `Salt Project's Ubuntu repository`_ and install the 20.04 packages.
```

2023-08-02 13:31 UTC, s0undt3ch commented
> would it be worth having a substitution var in the rst file instead of declaring the explicit 3006.1 number over and over?

How would that render in GitHub?

2023-08-02 17:15 UTC, ITJamie commented
> > would it be worth having a substitution var in the rst file instead of declaring the explicit 3006.1 number over and over?
> 
> How would that render in GitHub?

`.github/workflows/scripts/update-release-shasum.py` builds the actual readme.md file from the rst. 
a string replacement can be done here to always set the version number to the latest version (checking the salt repo as a reference i guess)

2023-08-08 18:37 UTC, s0undt3ch commented
> > > would it be worth having a substitution var in the rst file instead of declaring the explicit 3006.1 number over and over?
> > 
> > 
> > How would that render in GitHub?
> 
> `.github/workflows/scripts/update-release-shasum.py` builds the actual readme.md file from the rst. a string replacement can be done here to always set the version number to the latest version (checking the salt repo as a reference i guess)

Well, that does sound like a suggestion that is not impossible to implement.

@garethgreenaway thoughts?

2023-08-08 18:41 UTC, s0undt3ch requested changes

2023-08-08 18:41 UTC, s0undt3ch commented on README.rst
> +and ``AArch32`` (``armhf``). The latter is available only for Debian/Raspbian 8 platforms.
```suggestion
and ``AArch64`` (``arm64``).
```

2023-08-09 16:07 UTC, garethgreenaway commented
> > > > would it be worth having a substitution var in the rst file instead of declaring the explicit 3006.1 number over and over?
> > > 
> > > 
> > > How would that render in GitHub?
> > 
> > 
> > `.github/workflows/scripts/update-release-shasum.py` builds the actual readme.md file from the rst. a string replacement can be done here to always set the version number to the latest version (checking the salt repo as a reference i guess)
> 
> Well, that does sound like a suggestion that is not impossible to implement.
> 
> @garethgreenaway thoughts?

@s0undt3ch Woks for me.

2023-08-09 16:10 UTC, s0undt3ch commented
> > > > > would it be worth having a substitution var in the rst file instead of declaring the explicit 3006.1 number over and over?
> > > > 
> > > > 
> > > > How would that render in GitHub?
> > > 
> > > 
> > > `.github/workflows/scripts/update-release-shasum.py` builds the actual readme.md file from the rst. a string replacement can be done here to always set the version number to the latest version (checking the salt repo as a reference i guess)
> > 
> > 
> > Well, that does sound like a suggestion that is not impossible to implement.
> > @garethgreenaway thoughts?
> 
> @s0undt3ch Woks for me.

@ITJamie if you want to take a stab at it, we would be happy to review it.

2023-08-09 16:13 UTC, s0undt3ch approved these changes

2023-08-11 17:09 UTC, merged