Handle renaming of gnupg-curl to gnupg1-curl for Ubuntu 16.10
saltstack/salt-bootstrap pull request #998
Opened 2016-12-17 20:49 UTC by marco-m

### What does this PR do?

Handle renaming of gnupg-curl to gnupg1-curl for Ubuntu 16.10.

This allows to install salt on Ubuntu 16.10, tested with `bootstrap-salt.sh -M git v2016.11.1`

### What issues does this PR fix or reference?

Fixes at least partially #976

### Previous Behavior

Installing salt failed due to `gnupg-curl` non existing.

2016-12-17 20:54 UTC, marco-m commented
Jenkins fails with 

```
Groovy script failed:

groovy.lang.MissingPropertyException: No such property: msg for class: com.saltstack.jenkins.projects.Bootstrap
```

I don't know what it means :-)

2016-12-17 22:31 UTC, vutny requested changes
This is good enough. Thanks @marco-m !

Here is the correct link to the Jenkins build against your PR:
 https://jenkins-testing.saltstack.com/job/bootstrap/job/pr/job/998/job/lint/violations/file/bootstrap-salt.sh/

Got lintian error though. Could you please enclose `${DISTRO_VERSION}` variable in double quotes?

2016-12-18 13:51 UTC, marco-m commented
I addressed the lintian error regarding missing double quotes.



Note that, although this PR allows to succesfully install salt master and minion on Ubuntu 16.10, there are still bugs in bootstrap-salt.sh:

Running either `bootstrap-salt.sh` or `bootstrap-salt.sh git v2016.11.1`

will create the wrong APT entry (points to xenial instead than yakkety):

```
cd /etc/apt
find . -type f | xargs grep xenial
sources.list.d/saltstack.list:deb https://repo.saltstack.com/apt/ubuntu/16.10/amd64/latest xenial main
```
I have done these tests on a freshly upped vagrant.

2016-12-20 23:00 UTC, rallytime commented
@marco-m Good find! This same package name issue will likely hit Debian 9 as well (though I have not tried that yet).

2016-12-20 23:00 UTC, merged

2016-12-21 18:15 UTC, rallytime commented
@marco-m I made a follow up PR to this with #1001. It makes it so the `xenial` repo doesn't get added but adds a `yakkety` repo instead. That link will currently 404 unfortunately, but I think that is better than have the `xenial` link. If we end up making an official repo link for 16.10, then the bootstrap script will be ready to go.

2016-12-21 18:15 UTC, rallytime commented
See issue #976 for more discussion

2016-12-21 19:30 UTC, marco-m commented
@rallytime Thanks for the quick reaction. yes I agree, a 404 is better than a wrong link.